### ISSUE TITLE
菜单管理里页面显示适配有点问题

### ISSUE THREAD

**Issue by SimonFuu** [jachohx/urpm#1]
mac OS X，13寸 with retina，chrome 浏览器显示有点适配问题：
<img width="1029" alt="wx20170730-110707 2x" src="https://user-images.githubusercontent.com/18401434/28750261-97632c72-7517-11e7-8d22-121021bddf9b.png">

**Comment by jachohx** [comment]
谢谢反馈，这个问题最新版本已修复。已经增加了屏幕初始适应。
