### ISSUE TITLE
为何没有样式

### ISSUE THREAD

**Issue by ghost** [jachohx/urpm#13]

**Comment by ghost** [comment]
css没获取到

**Comment by jachohx** [comment]
如果是nginx 可以参与一下这个，https://github.com/jachohx/urpm#nginx%E5%8F%82%E8%80%83
apache不支持这些写法。如果要用apache的话，可以把 resources/assets下的目录一个一个ln到public下

**Comment by ghost** [comment]
嗯，我就是给放在了public下了，现在可以了，谢谢
