### ISSUE TITLE
请问Apache如何配置

### ISSUE THREAD

**Issue by 404LT** [jachohx/urpm#7]
您好，请问Apache应该如何配置这一段呢
location ~* \.(css|js|jpg|woff|woff2|png)$ {
        root /var/www/urpm/resources/assets/;
        break;
    }

**Comment by jachohx** [comment]
apache不支持这些写法。如果要用apache的话，可以把 resources/assets下的目录一个一个ln到public下

**Comment by 404LT** [comment]
非常感谢~
