### ISSUE TITLE
后台登陆点击后500

### ISSUE THREAD

**Issue by Wantfg** [jachohx/urpm#8]
Route::post('login',                    'LoginController@login');

在auth/LoginController ，没有login这个方法，是在哪里处理登陆信息吗？
我试过自己加一个login函数，能打印出东西

**Comment by jachohx** [comment]
用了laravel的用户认证，代码在
Auth/LoginController.php 的23行，use AuthenticatesUsers {authenticated as oriAuthenticated;}
你可以参考下文档：https://laravel-china.org/docs/laravel/5.5/authentication/1308
